spring.application.name=backend
#database
spring.datasource.url=jdbc:mysql://localhost:3306/expense_tracker
spring.datasource.username=root
spring.datasource.password=Narendra+2579
spring.datasourse.driver-class-name=com.mysql.cj.jdbc.Driver

#jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hiberante.dialect=org.hibernate.dialect.MySQLDialect

#server
server.port=8080





